### ISSUE TITLE
Bounds check

### ISSUE THREAD

**Issue by Type1J** [syoyo/nanovg-nanort#1]
Drawing out of bounds object causes a segfault.

Here's a demonstration:

```
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>
#include <nanovg.h>
#define NANOVG_RT_IMPLEMENTATION
#define NANORT_IMPLEMENTATION
#include <nanovg_rt.h>

void drawEyes(NVGcontext* vg, float x, float y, float w, float h, float mx, float my, float t)
{
  NVGpaint gloss, bg;
  float ex = w * 0.23f;
  float ey = h * 0.5f;
  float lx = x + ex;
  float ly = y + ey;
  float rx = x + w - ex;
  float ry = y + ey;
  float dx, dy, d;
  float br = (ex < ey ? ex : ey) * 0.5f;
  float blink = 1 - pow(sinf(t*0.5f), 200)*0.8f;

  bg = nvgLinearGradient(vg, x, y + h * 0.5f, x + w * 0.1f, y + h, nvgRGBA(0, 0, 0, 32), nvgRGBA(0, 0, 0, 16));
  nvgBeginPath(vg);
  nvgEllipse(vg, lx + 3.0f, ly + 16.0f, ex, ey);
  nvgEllipse(vg, rx + 3.0f, ry + 16.0f, ex, ey);
  nvgFillPaint(vg, bg);
  nvgFill(vg);

  bg = nvgLinearGradient(vg, x, y + h * 0.25f, x + w * 0.1f, y + h, nvgRGBA(220, 220, 220, 255), nvgRGBA(128, 128, 128, 255));
  nvgBeginPath(vg);
  nvgEllipse(vg, lx, ly, ex, ey);
  nvgEllipse(vg, rx, ry, ex, ey);
  nvgFillPaint(vg, bg);
  nvgFill(vg);

  dx = (mx - rx) / (ex * 10);
  dy = (my - ry) / (ey * 10);
  d = sqrtf(dx*dx + dy * dy);
  if (d > 1.0f) {
    dx /= d; dy /= d;
  }
  dx *= ex * 0.4f;
  dy *= ey * 0.5f;
  nvgBeginPath(vg);
  nvgEllipse(vg, lx + dx, ly + dy + ey * 0.25f*(1 - blink), br, br*blink);
  nvgFillColor(vg, nvgRGBA(32, 32, 32, 255));
  nvgFill(vg);

  dx = (mx - rx) / (ex * 10);
  dy = (my - ry) / (ey * 10);
  d = sqrtf(dx*dx + dy * dy);
  if (d > 1.0f) {
    dx /= d; dy /= d;
  }
  dx *= ex * 0.4f;
  dy *= ey * 0.5f;
  nvgBeginPath(vg);
  nvgEllipse(vg, rx + dx, ry + dy + ey * 0.25f*(1 - blink), br, br*blink);
  nvgFillColor(vg, nvgRGBA(32, 32, 32, 255));
  nvgFill(vg);

  gloss = nvgRadialGradient(vg, lx - ex * 0.25f, ly - ey * 0.5f, ex*0.1f, ex*0.75f, nvgRGBA(255, 255, 255, 128), nvgRGBA(255, 255, 255, 0));
  nvgBeginPath(vg);
  nvgEllipse(vg, lx, ly, ex, ey);
  nvgFillPaint(vg, gloss);
  nvgFill(vg);

  gloss = nvgRadialGradient(vg, rx - ex * 0.25f, ry - ey * 0.5f, ex*0.1f, ex*0.75f, nvgRGBA(255, 255, 255, 128), nvgRGBA(255, 255, 255, 0));
  nvgBeginPath(vg);
  nvgEllipse(vg, rx, ry, ex, ey);
  nvgFillPaint(vg, gloss);
  nvgFill(vg);
}

int main()
{
  NVGcontext* vg = nullptr;
  int winWidth = 1280, winHeight = 720;
  float pxRatio = 1280.0f / 720.0f;

  vg = nvgCreateRT(NVG_DEBUG, winWidth, winHeight);
  if (vg == nullptr) {
    printf("Could not init nanovg.\n");
    return -1;
  }

  nvgClearBackgroundRT(vg, 0.3f, 0.3f, 0.32f, 1.0f);

  nvgBeginFrame(vg, winWidth, winHeight, pxRatio); {
    drawEyes(vg, 20.0f, 50.0f, 40.0f, 40.0f, 20.0f, 20.0f, 1.0f); // Fine
    drawEyes(vg, winWidth - 20.0f - 50.0f, 50.0f, 40.0f, 40.0f, 20.0f, 20.0f, 1.0f); // Fine
    drawEyes(vg, winWidth - 20.0f, winHeight - 10.0f, 40.0f, 40.0f, 20.0f, 20.0f, 1.0f); // !!! SEGFAULT!
  } nvgEndFrame(vg);

  unsigned char* rgba = nvgReadPixelsRT(vg);
  stbi_write_png("render.png",  winWidth, winHeight, 4, rgba, winWidth * 4);

  nvgDeleteRT(vg);

  return 0;
}

```
See the line with the comment above that says `!!! SEGFAULT!`

**Comment by syoyo** [comment]
Thank you for reporting.

I got the following error by enabling address sanitizer. Will investigate the reason.

```
=================================================================
==7623==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00010c2a580c at pc 0x0001087ee74b bp 0x7ffee7478050 sp 0x7ffee7478048
READ of size 1 at 0x00010c2a580c thread T0
    #0 0x1087ee74a in rtnvg__alphaBlend(unsigned char*, float const*) nanovg_rt.h:1212
    #1 0x1087d836a in rtnvg__fill(RTNVGcontext*, RTNVGcall*) nanovg_rt.h:1547
    #2 0x1087b7b28 in rtnvg__renderFlush(void*) nanovg_rt.h:2021
    #3 0x1088219d7 in nvgEndFrame nanovg.c:310
    #4 0x1087bfd7a in main main.cc:92
    #5 0x7fff58980014 in start (libdyld.dylib:x86_64+0x1014)

0x00010c2a580c is located 12 bytes to the right of 3686400-byte region [0x00010bf21800,0x00010c2a5800)
allocated by thread T0 here:
    #0 0x1088cfe13 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x56e13)
    #1 0x1087b630f in nvgCreateRT nanovg_rt.h:2396
    #2 0x1087bfae4 in main main.cc:80
    #3 0x7fff58980014 in start (libdyld.dylib:x86_64+0x1014)

SUMMARY: AddressSanitizer: heap-buffer-overflow nanovg_rt.h:1212 in rtnvg__alphaBlend(unsigned char*, float const*)
Shadow bytes around the buggy address:
  0x100021854ab0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021854ac0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021854ad0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021854ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021854af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100021854b00: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x100021854b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x100021854b20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x100021854b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x100021854b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x100021854b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7623==ABORTING
Abort trap: 6
```
